# ConfigMap to expose configuration related to backend application
apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-conf # name of configMap
data:
  server-uri:  172.42.42.100:31397 # enternal ip of backend application 'Service'
